# Generated by Django 3.1.1 on 2020-09-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_company_file_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='file_news',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='file_csv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
